[package]
name = "rustdash"
version = "0.0.1"
authors = ["Kim Jeker <git@kije.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
